import type { NextPage } from "next";
import Head from "next/head";
import {
  Header,
  HeroSection,
  BrandsSection,
  TestimonialsSection,
  Footer,
  AboutMeSection,
  PortfolioSection,
} from "../components";
import { getAllPosts, PortfolioType } from "../lib/api";

type HomeProps = {
  allPortfolios: PortfolioType[];
};

const Home: NextPage<HomeProps> = ({ allPortfolios }: HomeProps) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <HeroSection />
      <AboutMeSection />
      <PortfolioSection portfolios={allPortfolios} />
      <BrandsSection />
      <TestimonialsSection />
      <Footer />
    </>
  );
};

export async function getStaticProps() {
  const allPortfolios = getAllPosts([
    "title",
    "date",
    "slug",
    "author",
    "coverImage",
    "excerpt",
  ]);

  return {
    props: { allPortfolios },
  };
}

export default Home;
