import Head from "next/head";
import React from "react";

type MetaProps = {
  title?: string;
  children?: React.ReactNode;
};

const Meta = ({ title, children }: MetaProps) => (
  <Head>
    <title>Lenka Wallace {title && ` - ${title}`}</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
    {children}
  </Head>
);

export default Meta;